# Generated by Django 3.0.5 on 2020-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mifga', '0002_auto_20200511_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='mifga',
            name='obs_title',
            field=models.CharField(choices=[('מקלטים', 'מקלטים'), ('נקיון', 'נקיון'), ('פארקים', 'פארקים'), ('רמזורים', 'רמזורים'), ('כבישים ומדרכות', 'כבישים ומדרכות'), ('מוסדות חינוך', 'מוסדות חינוך'), ('מים', 'מים'), ('מצלמות', 'מצלמות'), ('בעלי חיים', 'בעלי חיים'), ('גינון', 'גינון'), ('חניה', 'חניה'), ('חשמל ותאורה', 'חשמל ותאורה'), ('ביוב', 'ביוב'), ('אחר', 'אחר')], default='אחר', max_length=255),
        ),
    ]
