# Generated by Django 3.0.5 on 2020-05-11 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mifga', '0004_mifga_agent_att'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mifga',
            name='agent_att',
        ),
        migrations.AddField(
            model_name='mifga',
            name='agent_att',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Mifga.agent_att+', to=settings.AUTH_USER_MODEL),
        ),
    ]
