# Generated by Django 3.0.5 on 2020-05-11 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mifga', '0008_auto_20200511_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mifga',
            name='agent_att',
        ),
        migrations.AddField(
            model_name='mifga',
            name='agent_att',
            field=models.ManyToManyField(related_name='_mifga_agent_att_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
