# Generated by Django 3.0.5 on 2020-05-11 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mifga', '0011_auto_20200511_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mifga',
            name='agent_att',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Mifga.author+', to=settings.AUTH_USER_MODEL),
        ),
    ]
