# Generated by Django 3.0.5 on 2020-05-30 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mifga', '0012_auto_20200511_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='mifga',
            name='subscribed_issues',
            field=models.ManyToManyField(related_name='_mifga_subscribed_issues_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mifga',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
