# Generated by Django 3.0.5 on 2020-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mifga', '0017_auto_20200530_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mifga',
            name='subscribed_to_issue',
        ),
        migrations.AddField(
            model_name='mifga',
            name='subscribed_to_issue',
            field=models.TextField(default=''),
        ),
    ]
